version: '3'

services:

  web:
      build: .
      volumes:
        - .:/app
      tty: true
      command:
        sh -c "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
      ports:
        - "8080:8080"
